name: $(version).$(Rev:r)

variables:
  version: 3.0
  buildConfiguration: "Release"
  imageRepository: "emberstack/sftp"
  DOCKER_CLI_EXPERIMENTAL: 'enabled'

trigger:
  branches:
    include:
      - "*"
  paths:
    include:
    - src/*
    - .devops/*
    - azure-pipelines.yaml

stages:
- template: .devops/pipelines/stage.ci.yaml
  parameters:
    architectures:
    - arch: amd64
      pool: winromulus-devops
    - arch: arm
      pool: winromulus-devops
    - arch: arm64
      pool: winromulus-devops


- template: .devops/pipelines/stage.cd.yaml
  parameters:
    architectures:
    - arch: amd64
    - arch: arm
    - arch: arm64