{{- if .Values.extraService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.extraService.name }}
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
  {{- with .Values.extraService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if ne .Values.extraService.type "NodePort" }}
{{- if .Values.extraService.clusterIP }}
  clusterIP: "{{ .Values.extraService.clusterIP }}"
{{- end }}
{{- end }}
{{- if .Values.extraService.externalIPs }}
  externalIPs:
{{ toYaml .Values.extraService.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.extraService.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.extraService.loadBalancerIP }}"
{{- end }}
{{- if .Values.extraService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.extraService.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.extraService.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.extraService.externalTrafficPolicy }}"
{{- end }}
  type: {{ .Values.extraService.type }}
  ports:
    - port: {{ .Values.extraService.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "sftp.selectorLabels" . | nindent 4 }}
{{- end }}