version: '3'
services:
  sftp:
    image: "emberstack/sftp:dev"
    build:
      context: ../../src
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    volumes:
    - ../samples/sample.dev.sftp.json:/sftp/config/sftp.json:ro
    - ../samples/.ssh/id_demo_rsa.pub:/home/demo/.ssh/keys/id_rsa.pub:ro
    - ../samples/.ssh/id_demo2_rsa.pub:/home/demo2/.ssh/keys/id_rsa.pub:ro